# -*- Makefile -*-

CFLAGS := -g -O2
CXXFLAGS := -g -O2 -O2
LDFLAGS :=  -lstdc++

# use the darmin test as a proxy for detecting Mac OS X
ifneq ($(shell uname -s), Darwin)
  CFLAGS += -static
endif

CXXFLAGS += -Wall -DEXT_HASH_MAP -std=c++0x -fno-omit-frame-pointer

LEX := flex
YACC := bison -d -y --debug -v
RANLIB := ranlib
