base64 12 dslab-worf.epfl.ch 12 chcon 12 dslab-worf.epfl.ch 12 chgrp 12 dslab-worf.epfl.ch 12 chmod 12 dslab-worf.epfl.ch 12 chown 12 dslab-picard.epfl.ch 12 cksum 12 dslab-picard.epfl.ch 12
comm 12 dslab-worf.epfl.ch 12 cp 12 dslab-worf.epfl.ch 12 csplit 12 dslab-worf.epfl.ch 12 cut 12 dslab-worf.epfl.ch 12 date 12 dslab-picard.epfl.ch 12 dd 12 dslab-picard.epfl.ch 12
df 12 dslab-worf.epfl.ch 12 dir 12 dslab-worf.epfl.ch 12 dircolors 12 dslab-worf.epfl.ch 12 dirname 12 dslab-worf.epfl.ch 12 du 12 dslab-picard.epfl.ch 12 env 12 dslab-picard.epfl.ch 12
expand 12 dslab-worf.epfl.ch 12 expr 12 dslab-worf.epfl.ch 12 factor 12 dslab-worf.epfl.ch 12 fmt 12 dslab-worf.epfl.ch 12 fold 12 dslab-picard.epfl.ch 12 ginstall 12 dslab-picard.epfl.ch 12
head 12 dslab-worf.epfl.ch 12 hostid 12 dslab-worf.epfl.ch 12 id 12 dslab-worf.epfl.ch 12 join 12 dslab-worf.epfl.ch 12 kill 12 dslab-picard.epfl.ch 12 link 12 dslab-picard.epfl.ch 12
ln 12 dslab-worf.epfl.ch 12 ls 12 dslab-worf.epfl.ch 12 mkdir 12 dslab-worf.epfl.ch 12 mknod 12 dslab-worf.epfl.ch 12 mv 12 dslab-picard.epfl.ch 12 nice 12 dslab-picard.epfl.ch 12
nl 12 dslab-worf.epfl.ch 12 od 12 dslab-worf.epfl.ch 12 paste 12 dslab-worf.epfl.ch 12 pinky 12 dslab-worf.epfl.ch 12 pr 12 dslab-picard.epfl.ch 12 printf 12 dslab-picard.epfl.ch 12
ptx 12 dslab-worf.epfl.ch 12 pwd 12 dslab-worf.epfl.ch 12 readlink 12 dslab-worf.epfl.ch 12 rm 12 dslab-worf.epfl.ch 12 rmdir 12 dslab-picard.epfl.ch 12 seq 12 dslab-picard.epfl.ch 12
setuidgid 12 dslab-worf.epfl.ch 12 sha384sum 12 dslab-worf.epfl.ch 12 sha512sum 12 dslab-worf.epfl.ch 12 shred 12 dslab-worf.epfl.ch 12 shuf 12 dslab-picard.epfl.ch 12 sleep 12 dslab-picard.epfl.ch 12
sort 12 dslab-worf.epfl.ch 12 split 12 dslab-worf.epfl.ch 12 stat 12 dslab-worf.epfl.ch 12 sum 12 dslab-worf.epfl.ch 12 tac 12 dslab-picard.epfl.ch 12 tail 12 dslab-picard.epfl.ch 12
test 12 dslab-worf.epfl.ch 12 touch 12 dslab-worf.epfl.ch 12 tr 12 dslab-worf.epfl.ch 12 tsort 12 dslab-worf.epfl.ch 12 tty 12 dslab-picard.epfl.ch 12 uname 12 dslab-picard.epfl.ch 12
unexpand 12 dslab-worf.epfl.ch 12 uniq 12 dslab-worf.epfl.ch 12 unlink 12 dslab-worf.epfl.ch 12 users 12 dslab-worf.epfl.ch 12 vdir 12 dslab-picard.epfl.ch 12 wc 12 dslab-picard.epfl.ch 12
who 12 dslab-worf.epfl.ch 12 whoami 12 dslab-worf.epfl.ch 12
