#!/bin/bash
#
# Transform libtool to compile to LLVM
#
export KLEE_GCC="/home/sun/esd-work/git/cloud9/scripts/klee-gcc" 
sed -i "s|AR=\"ar\"|AR=\"llvm-ar\"|" libtool
sed -i "s|LTCC=\"gcc\"|LTCC=\""$KLEE_GCC"\"|" libtool
sed -i "s|CC=\"gcc\"|CC=\""$KLEE_GCC"\"|" libtool
sed -i "s|CC=\"g++\"|CC=\""$KLEE_GCC"\"|" libtool
